language: python
python: 3.5
dist: trusty
sudo: true
services:
  - docker


before_install:
  - docker pull enhancedsociety/solsa

before_script:
  - function solsa () { docker run -it --rm -v $(pwd):/src:ro enhancedsociety/solsa $@ }

script:
  - for contract in $(ls contracts/test/); do echo $contract; solsa -a contracts/test/$contract; echo;done



