version: '2'
services:
    tkn:
        build:
          context: .
          dockerfile: Dockerfile
        container_name: tkn
        tty: true
        networks:
          testnet:
            ipv4_address: 172.21.0.3
        volumes:
          - "./contracts:/usr/src/app/contracts"
          - "./crowdsales:/usr/src/app/crowdsales"
          - "./zeppelin:/usr/src/app/zeppelin"
          - "./ico:/usr/src/app/ico"
          - "./populus.json:/usr/src/app/populus.json"

networks:
  testnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
